### ISSUE TITLE
IllegalArgumentException when using condition in 'depends_on'

### ISSUE THREAD

**Issue by maudrid** [derlin/docker-compose-viz-mermaid#4]
When using this syntax in docker compose:
```
depends_on:
      postgres:
        condition: service_healthy
      sqitch:
        condition: service_completed_successfully
```

The following error is raised:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected type for list {postgres={condition=service_healthy}, sqitch={condition=service_completed_successfully}}
        at ch.derlin.dcvizmermaid.data.Service.linksFromDependsOn(Service.kt:78)
        at ch.derlin.dcvizmermaid.data.Service.links(Service.kt:9)
        at ch.derlin.dcvizmermaid.data.DockerCompose$links$2.invoke(DockerCompose.kt:17)
        at ch.derlin.dcvizmermaid.data.DockerCompose$links$2.invoke(DockerCompose.kt:17)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ch.derlin.dcvizmermaid.data.DockerCompose.getLinks(DockerCompose.kt:17)
        at ch.derlin.dcvizmermaid.data.DockerCompose$extendedLinks$2.invoke(DockerCompose.kt:21)
        at ch.derlin.dcvizmermaid.data.DockerCompose$extendedLinks$2.invoke(DockerCompose.kt:20)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ch.derlin.dcvizmermaid.data.DockerCompose.getExtendedLinks(DockerCompose.kt:20)
        at ch.derlin.dcvizmermaid.GenerateGraph.addLinks(GenerateGraph.kt:75)
        at ch.derlin.dcvizmermaid.GenerateGraph.invoke(GenerateGraph.kt:42)
        at ch.derlin.dcvizmermaid.Cli.run(Cli.kt:93)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:170)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
        at ch.derlin.dcvizmermaid.MainKt.main(main.kt:3)
```

**Comment by derlin** [comment]
Thanks for raising this issue!
The code indeed doesn't expect a map under depends_on... I will have to change a bit the model. Will try to do it this week (except if you want to try 😉).

I'll keep you updated!
